name: Build
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: "16.18.1"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
